<a href="https://colab.research.google.com/github/nurbekdev/DataSciene/blob/main/%2307_arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arifmetik amallar

### NumPy kutubxonasini chaqirib olamiz

In [1]:
import numpy as np

### Ko'paytirish amalli

In [5]:
#data
arr1 = np.arange(6).reshape(2, 3)
arr2 = np.arange(6, 12).reshape(2, 3)

In [7]:
# Ko'paytish
arr1* arr2 # arr1 ning elementlarini arr2 mos elemntlariga ko'paytirib beradi

array([[ 0,  7, 16],
       [27, 40, 55]])

In [8]:
# Bo'lish
arr2 / arr1 # arr2 ning barcha elementlarini arr1 mos elemtlariga bo'ladi

<ipython-input-8-348274337a8c>:2: RuntimeWarning: divide by zero encountered in true_divide
  arr2 / arr1 # arr2 ning barcha elementlarini arr1 mos elemtlariga bo'ladi


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

In [9]:
# Qo'shish
arr1 + arr2

array([[ 6,  8, 10],
       [12, 14, 16]])

In [11]:
# Ayirish
arr2 - arr1 # arr2 ning elementlaridan arr1 ning mos elemtlarini ayiradi

array([[6, 6, 6],
       [6, 6, 6]])

In [12]:
# Kvadratga oshirish (square)
arr1 ** 2

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [13]:
# Kvadrat ildizdan chiqarish (sqrt)
arr2 ** 0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])