<a href="https://colab.research.google.com/github/nurbekdev/DataSciene/blob/main/%2311_fayllar_bn_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Fayllar bilan ishlash

### NumPy kutubxonasini chaqirib olamiz

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data',arr) # data fayliga arrayning ma'lumotlarini yozish

In [6]:
arr2 = np.load('data.npy') # data.npy faylidan ma'lumotlarni o'qish
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [8]:
np.savez('arrays', a = arr, b = arr1)

In [9]:
arrays = np.load('arrays.npz')

In [10]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Faylni hajmi kichraytirib saqlash

In [12]:
np.savez_compressed('array_comp.npz', a = arr, b = arr1)