<a href="https://colab.research.google.com/github/nurbekdev/DataSciene/blob/main/%2305_universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Universal funksiyalar

In [2]:
import numpy as np

### Unary funksiyalar (Bitta qiymat qabul qiluvchi)

### `sqrt`, `square`, `exp`, `log`, `modf`, `sign`, `isnan` funksiyalari

In [4]:
arr = np.arange(10) # 0~10 bo'lgan massivni 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `sqrt` massivning xar bir elementing kvadrat ildizni qaytaradi

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

### `square` massining xar bir elemeni kvadaratga oshiradi

In [6]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### `exp` massivning xar bir elementing exponentini qaytaradi

In [7]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

### `log` massivning har bir elementining logarifimini qaytaradi

In [9]:
np.log(arr[2:])

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458])

### `modf` haqiqiy sonlaring butun va qoldiq qismini ajratib beruvchi funksiya

In [14]:
arr1 = np.random.randn(6)
arr1

array([ 1.55013831, -0.90524678, -0.06099761, -0.34933876,  0.16182196,
       -1.6686241 ])

In [15]:
qoldiq, butun = np.modf(arr1)
print(qoldiq)
print(butun)

[ 0.55013831 -0.90524678 -0.06099761 -0.34933876  0.16182196 -0.6686241 ]
[ 1. -0. -0. -0.  0. -1.]


### `sign` massiv elementi manfiy bo'lsa `-1` aksincha `1` ni qaytaradi

In [16]:
np.sign(arr1)

array([ 1., -1., -1., -1.,  1., -1.])

# Binary funksiyalar (Ikkta argument qabul qiluvchi)

### `add`, `multiply`, `maximum` funksiyalar

### `add` ikkta massivning mos elementlarini qo'shadi

In [17]:
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)
print(arr2)
print(arr3)

[-1.50857382 -0.25637514  1.46354733  0.74916624  0.91424324  1.11496013]
[ 0.64376287  1.58417858 -0.02446206  0.28420775  1.63111838 -0.89361998]


In [19]:
np.add(arr2,arr3) # arr2 va arr3 ning mos elementlarini qo'shib beradi

array([-0.86481095,  1.32780344,  1.43908527,  1.033374  ,  2.54536163,
        0.22134015])

In [21]:
arr2 + arr3 # yuqoridagi funksiya bilan bir xil

array([-0.86481095,  1.32780344,  1.43908527,  1.033374  ,  2.54536163,
        0.22134015])

### `multipy` ikkita massivning mos elemntlarini ko'paytiradi

In [22]:
np.multiply(arr2, arr3)

array([-0.97116381, -0.40614401, -0.03580139,  0.21291885,  1.49123896,
       -0.99635064])

### `maximum` ikkita massivning elementlarin taqqoslab ulardan kattasining qiymatini qaytaradi

In [23]:
np.maximum(arr2, arr3)

array([0.64376287, 1.58417858, 1.46354733, 0.74916624, 1.63111838,
       1.11496013])