<a href="https://colab.research.google.com/github/nurbekdev/DataSciene/blob/main/%2309_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tartiblash (`Sorting`)

### NumPy kutubxonasini chaqirib olamiz

In [1]:
import numpy as np

### `Sorting`

In [3]:
#data
arr = np.random.rand(4) # 4 ta taxminiy elemtlardan tashkil topgan massiv
arr

array([0.76560794, 0.67905804, 0.06903647, 0.46094022])

### `sort` funksiyasi

In [6]:
# 1-usul
sorted_arr = np.sort(arr) # arrayning barcha elemtlarini tartiblagan holda chop etish
sorted_arr

array([0.06903647, 0.46094022, 0.67905804, 0.76560794])

In [7]:
# 2-usul
arr.sort()
arr

array([0.06903647, 0.46094022, 0.67905804, 0.76560794])

In [8]:
# teskari tartibda tartiblash
rev_arr = -np.sort(-arr)
rev_arr

array([0.76560794, 0.67905804, 0.46094022, 0.06903647])

In [9]:
# 2 d massiv
arr2d = np.random.randn(2, 4) # (2, 4) massiv
arr2d

array([[-1.63238436,  0.46832615, -0.44060803, -0.95053685],
       [ 0.33158843, -0.04125327, -0.27310061,  1.38788423]])

In [10]:
row_srt = np.sort(arr2d, axis = 0) # axis = 0 --> Qator
row_srt

array([[-1.63238436, -0.04125327, -0.44060803, -0.95053685],
       [ 0.33158843,  0.46832615, -0.27310061,  1.38788423]])

In [11]:
col_srt = np.sort(arr2d, axis = 1) # axis = 1 --> Ustun
col_srt

array([[-1.63238436, -0.95053685, -0.44060803,  0.46832615],
       [-0.27310061, -0.04125327,  0.33158843,  1.38788423]])