<a href="https://colab.research.google.com/github/nurbekdev/DataSciene/blob/main/%2304_Transposing%26Swapping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Massiv o'qlarini almashtish 
### Transpsoing va Swapping

In [2]:
import numpy as np #Numpy kutubxonasini chaqirib olamiz

### Massivlar pozitsiyasini ko'chirish `Transpose` va o'qlar o'rnini almashtirish `Swapping axes`

In [3]:
A = np.arange(6).reshape(3,2) # (3, 2) bo'lgan Massiv
A

array([[0, 1],
       [2, 3],
       [4, 5]])

# `Transpose`

In [4]:
A.T # A massivni Tranpose holatini beradi

array([[0, 2, 4],
       [1, 3, 5]])

### `Swapping axes`

In [5]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [8]:
A.swapaxes(1, 0) # A massivni Transpose ko'rinishini beradi

array([[0, 2, 4],
       [1, 3, 5]])

### Misol: AA^T

In [9]:
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
np.dot(A, A.T) # AA^T dan hosil bo'lgan massiv

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])