<a href="https://colab.research.google.com/github/nurbekdev/DataSciene/blob/main/%2306_logical_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mantiqiy shart operatorlarini massiv operatori sifatida foydalanish

In [1]:
import numpy as np # NumPy kutubxonasini chaqirib olamiz

In [2]:
#massivlar
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
print(xarr)
print(yarr)

[1.1 1.2 1.3 1.4 1.5]
[2.1 2.2 2.3 2.4 2.5]


In [3]:
#Shart
cond = np.array([True, False, True, True, False])

In [4]:
# where
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [5]:
arr = np.random.randn(4, 4)  # (4, 4) taxminiy massiv
arr

array([[-0.31674198,  0.04474111, -0.16249951, -0.81209565],
       [ 0.39779382,  0.03528995,  0.95618266,  0.73157371],
       [ 1.99115788, -0.96627213, -0.55718149,  0.00724628],
       [-0.59731068,  1.92265463, -1.91846184, -0.80552244]])

In [6]:
# where
results = np.where(arr<0, -2, 2) # arr ning manfiy elementlarini -2 ga musbat elementlarin esa 2 ga almashitirish
results

array([[-2,  2, -2, -2],
       [ 2,  2,  2,  2],
       [ 2, -2, -2,  2],
       [-2,  2, -2, -2]])