<a href="https://colab.research.google.com/github/nurbekdev/DataSciene/blob/main/%2308_Math%26Stat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matematik va Statistik usullarni qo'llash

### NumPy kutubxonasini chaqirib olamiz

In [2]:
import numpy as np

In [3]:
# dataz
arr1 = np.random.randn(5, 4)
arr1

array([[ 1.85589667, -0.08879988,  0.73905934,  1.08975893],
       [-1.16614399, -0.43057731,  1.12124168, -1.50567126],
       [-0.73682007,  0.39729497,  0.50496174,  1.39353131],
       [-0.02383626, -1.2660796 ,  0.56964829,  0.5276619 ],
       [-0.87565893, -1.69922827, -0.32639833,  1.22334786]])

### `sum` metodi

In [5]:
arr1.sum() # arrayning barcha elemtlarini yig'indisini hisoblab beradi

1.3031887881493038

In [6]:
np.sum(arr1)

1.3031887881493038

In [7]:
arr1.sum(axis=1) # qator bo'yicha yig'indi

array([ 3.59591506, -1.98115088,  1.55896795, -0.19260566, -1.67793768])

In [8]:
arr1.sum(axis=0) # ustun bo'yicha yig'indi

array([-0.94656257, -3.08739009,  2.60851272,  2.72862874])

### `mean` metodi 

In [9]:
#sodda ma'lumot
arr2 = np.arange(6) # 0~6 gacha bo'lgan
arr2

array([0, 1, 2, 3, 4, 5])

In [11]:
#qo'lda hisoblab ko'ramiz
result = np.sum(arr2)/len(arr2)
result

2.5

In [12]:
np.mean(arr2)

2.5

In [13]:
arr2.mean()

2.5

In [14]:
arr1

array([[ 1.85589667, -0.08879988,  0.73905934,  1.08975893],
       [-1.16614399, -0.43057731,  1.12124168, -1.50567126],
       [-0.73682007,  0.39729497,  0.50496174,  1.39353131],
       [-0.02383626, -1.2660796 ,  0.56964829,  0.5276619 ],
       [-0.87565893, -1.69922827, -0.32639833,  1.22334786]])

In [15]:
arr1.mean() # arr1 ning o'rtacha qiymati

0.06515943940746519

In [16]:
np.mean(arr1)

0.06515943940746519

In [17]:
np.mean(arr1, axis=1) # qator bo'yicha o'rtacha qiymat

array([ 0.89897877, -0.49528772,  0.38974199, -0.04815142, -0.41948442])

In [18]:
arr1.mean(axis=0) # uston bo'yicha o'rtacha qiymat

array([-0.18931251, -0.61747802,  0.52170254,  0.54572575])

### `cumsum` metodi

In [19]:
arr2

array([0, 1, 2, 3, 4, 5])

In [20]:
arr2.cumsum()

array([ 0,  1,  3,  6, 10, 15])